### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 

### ISSUE THREAD

**Issue by kirqwer6666** [GlassyWu/KTDN#1]
Hi, when running your test program, i met this question? I cannot handle it. Can you help me? Thank you!
====================================
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    net = Dehaze()
  File "C:\Users\zyq\Desktop\ktdn\model.py", line 255, in __init__
    res2net101.load_state_dict(model_zoo.load_url(model_urls['res2net101_v1b_26w_4s']))
  File "D:\anaconda\envs\dehaze\lib\site-packages\torch\hub.py", line 559, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "D:\anaconda\envs\dehaze\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda\envs\dehaze\lib\site-packages\torch\serialization.py", line 774, in _legacy_load
    result = unpickler.load()
  File "D:\anaconda\envs\dehaze\lib\site-packages\torch\serialization.py", line 730, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "D:\anaconda\envs\dehaze\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "D:\anaconda\envs\dehaze\lib\site-packages\torch\serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "D:\anaconda\envs\dehaze\lib\site-packages\torch\serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the C
PU.
============================================

**Comment by ghost** [comment]
open the resnet.py, and recify the cuda path to 0 or just annotation it
